name: "Send Push"

on:
  schedule:
    - cron: "*/10 * * * *"
  push:
    branches: [master]

jobs:
  send-push:
    runs-on: ubuntu-latest
    steps:
      - name: Send push
        run: curl -d 'adminPassword=${{ secrets.ADMIN_PASSWORD }}' -X POST https://collegetable.vercel.app/api/sendPushTest
